---
Organizations:
    - &orderer
        Name: orderer
        ID: ordererMSP
        MSPDir: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/ordererOrganizations/pharma-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ordererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ordererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ordererMSP.admin')"
    - &consumer
        Name: consumerMSP
        ID: consumerMSP
        MSPDir: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/peerOrganizations/consumer.pharma-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('consumerMSP.admin', 'consumerMSP.peer', 'consumerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('consumerMSP.admin', 'consumerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('consumerMSP.admin')"      
            Endorsement:
                Type: Signature
                Rule: "OR('consumerMSP.peer')"        
        AnchorPeers: 
            - Host: peer0.consumer.pharma-network.com
              Port: 7051 
    - &distributor
        Name: distributorMSP
        ID: distributorMSP
        MSPDir: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/peerOrganizations/distributor.pharma-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('distributorMSP.admin', 'distributorMSP.peer', 'distributorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('distributorMSP.admin', 'distributorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('distributorMSP.admin')"      
            Endorsement:
                Type: Signature
                Rule: "OR('distributorMSP.peer')"        
        AnchorPeers: 
            - Host: peer0.distributor.pharma-network.com
              Port: 9051 
    - &manufacturer
        Name: manufacturerMSP
        ID: manufacturerMSP
        MSPDir: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/peerOrganizations/manufacturer.pharma-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('manufacturerMSP.admin', 'manufacturerMSP.peer', 'manufacturerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('manufacturerMSP.admin', 'manufacturerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('manufacturerMSP.admin')"      
            Endorsement:
                Type: Signature
                Rule: "OR('manufacturerMSP.peer')"        
        AnchorPeers: 
            - Host: peer0.manufacturer.pharma-network.com
              Port: 11051 
    - &retailer
        Name: retailerMSP
        ID: retailerMSP
        MSPDir: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/peerOrganizations/retailer.pharma-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('retailerMSP.admin', 'retailerMSP.peer', 'retailerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('retailerMSP.admin', 'retailerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('retailerMSP.admin')"      
            Endorsement:
                Type: Signature
                Rule: "OR('retailerMSP.peer')"        
        AnchorPeers: 
            - Host: peer0.retailer.pharma-network.com
              Port: 13051 
    - &transporter
        Name: transporterMSP
        ID: transporterMSP
        MSPDir: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/peerOrganizations/transporter.pharma-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('transporterMSP.admin', 'transporterMSP.peer', 'transporterMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('transporterMSP.admin', 'transporterMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('transporterMSP.admin')"      
            Endorsement:
                Type: Signature
                Rule: "OR('transporterMSP.peer')"        
        AnchorPeers: 
            - Host: peer0.transporter.pharma-network.com
              Port: 15051 
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer1.pharma-network.com:7050
        - orderer2.pharma-network.com:7050
        - orderer3.pharma-network.com:7050

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 98 MB
        PreferredMaxBytes: 512 KB
    EtcdRaft:
        Consenters:
            - Host: orderer1.pharma-network.com
              Port: 7050
              ClientTLSCert: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/ordererOrganizations/pharma-network.com/orderers/orderer1.pharma-network.com/tls/server.crt
              ServerTLSCert: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/ordererOrganizations/pharma-network.com/orderers/orderer1.pharma-network.com/tls/server.crt 
            - Host: orderer2.pharma-network.com
              Port: 7050
              ClientTLSCert: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/ordererOrganizations/pharma-network.com/orderers/orderer2.pharma-network.com/tls/server.crt
              ServerTLSCert: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/ordererOrganizations/pharma-network.com/orderers/orderer2.pharma-network.com/tls/server.crt 
            - Host: orderer3.pharma-network.com
              Port: 7050
              ClientTLSCert: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/ordererOrganizations/pharma-network.com/orderers/orderer3.pharma-network.com/tls/server.crt
              ServerTLSCert: /home/ravi/upgrad3196capstone/blockchainNetwork/crypto-config/ordererOrganizations/pharma-network.com/orderers/orderer3.pharma-network.com/tls/server.crt 
           
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    RaftOrderer:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
            - *orderer
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *orderer
        Consortiums:
            Consortiumpharmachannel:
                Organizations:
                   - *consumer
                   - *distributor
                   - *manufacturer
                   - *retailer
                   - *transporter
    pharmachannel:
        Consortium: Consortiumpharmachannel
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *consumer
                - *distributor
                - *manufacturer
                - *retailer
                - *transporter
            Capabilities:
                <<: *ApplicationCapabilities
