OrdererOrgs:
  - Name: Orderer
    Domain: pharma-network.com
    Specs:
      - Hostname: orderer1
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer2
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer3
        SANS:
          - "localhost"
          - "127.0.0.1"
        

        
PeerOrgs:
 - Name: manufacturer
   Domain: manufacturer.pharma-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 0
 - Name: distributor
   Domain: distributor.pharma-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 0
 - Name: retailer
   Domain: retailer.pharma-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 0
 - Name: consumer
   Domain: consumer.pharma-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 0
 - Name: transporter
   Domain: transporter.pharma-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 0
